name: 1000emetro
favicon: null
layout_spectrum: 0.072759477654472
typography_spectrum: 0.6150615692604333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8521330838557333
  lightness: 0.0895258414093405
  saturation: 0.09713999344967306
  rhythmicContrast: 0.0176166535820812
purpose: []
